create database pethappy
go

use pethappy
go

--creamos la tabla cliente		

CREATE TABLE CLIENTE
(	
	CODCLI CHAR(5),
	NOMCLI VARCHAR(80),
	APECLI VARCHAR(80),
	DNICLI CHAR(8),
	CELCLI CHAR(9),
	EMACLI VARCHAR(100),
	DIRCLI VARCHAR(100),
	ESTCLI CHAR(1) DEFAULT 'A',  -- Agrega por default el estado A (activo)
	UBICLI CHAR(5)
	CONSTRAINT CODCLI_PK PRIMARY KEY (CODCLI) -- Definiendo clave principal
)
GO
--creamos la tabla vendedor
CREATE TABLE VENDEDOR
(	
	CODVEND CHAR(5),
	NOMVEND VARCHAR(80),
	APEVEND VARCHAR(80),
	DNIVEND CHAR(8),
	CELVEND CHAR(9),
	EMAVEND VARCHAR(100),
	DIRVEND VARCHAR(100),
	ESTVEND CHAR(1)DEFAULT 'A',  -- Agrega por default el estado A (activo)
	UBIVEND CHAR(5)
	CONSTRAINT CODVEND_PK PRIMARY KEY (CODVEND) -- Definiendo clave principal
)
GO
--creamos la tabla producto
CREATE TABLE PRODUCTO
(	
	CODPRO CHAR(5),
	NOMPRO VARCHAR(80),
	PRECPRO DECIMAL(8,2),
	CANTPRO INT,
	CONSTRAINT CODPRO_PK PRIMARY KEY (CODPRO) -- Definiendo clave principal
)
GO

--creamos la tabla venta
CREATE TABLE VENTA
( 
	IDVENT  INT,  
	FECHVENT DATETIME DEFAULT GETDATE(), 
	CODCLI  CHAR(5),
	CODVEND CHAR(5),
	CODPRO CHAR(5),
	CANTVENT INT
	CONSTRAINT IDVENT_PK PRIMARY KEY (IDVENT)
)
GO

--creamos la tabla venta detalle
CREATE TABLE VENTA_DETALLE
(
	IDVENTDET INT  IDENTITY(1,1),
	IDVENT  INT,
	CODPRO CHAR(5),
	NOMPRO VARCHAR(80),
	CANTPRO INT	
	CONSTRAINT IDVENTDET_PK PRIMARY KEY (IDVENTDET)
)
GO

--establecemos las relaciones
ALTER TABLE VENTA 
ADD CONSTRAINT VENTA_CLIENTE
FOREIGN KEY (CODCLI)
REFERENCES CLIENTE (CODCLI)
GO

ALTER TABLE VENTA 
ADD CONSTRAINT VENTA_VENDEDOR
FOREIGN KEY (CODVEND)
REFERENCES VENDEDOR (CODVEND)
GO

ALTER TABLE VENTA_DETALLE
ADD CONSTRAINT VENTA_DETALLE_PRODUCTO
FOREIGN KEY (CODPRO)
REFERENCES PRODUCTO (CODPRO)
GO

ALTER TABLE VENTA_DETALLE
ADD CONSTRAINT VENTA_DETALLE_VENTA
FOREIGN KEY (IDVENT)
REFERENCES VENTA (IDVENT)
GO

--INSERTAMOS REGISTROS CLIENTES
INSERT INTO CLIENTE
(CODCLI,NOMCLI,APECLI,DNICLI,CELCLI,EMACLI,DIRCLI)
VALUES
('P0001','Alberto','Corrales Lozada','15363798','','alberto.corrales@yahoo.com','Calle Los Portales'),
('P0002','Juana','Sánchez Ortega','13256497','974815258','juana.sanchez@yahoo.com','Av.La Libertad'),
('P0003','Javier','Nakasone Villa','15953575','995236147','javier.nakasone@yahoo.com','Jr.San Martín'),
('P0004','Sonia','Huayta Medina','','12657814','sonia.huayta@yahoo.com','Av.Las Gardenias'),
('P0005','Fabiano','Carrión Ávila','','12233647','','Jr.Huancayo')
GO

SELECT*FROM CLIENTE
GO





